<?php




/**
 * @file
 * Music Search module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\Entity\NodeType;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\field\Entity\FieldConfig;

/**
 * Implements hook_help().
 */
function music_search_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.music_search':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is an example module.') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_theme()
 */
function music_search_theme() {
  return [
    'music_search_page' => [
      'variables' =>['form' => NULL],
    ],
  ];
}


/**
 * Implements hook_install()
 *
 * Installs content types if they dont exist,
 * Makes this module movable to other projects
 */

function music_search_install() {
  if (!NodeType::load('artist')) {
    NodeType::create([
      'type' => 'listamadur',
      'name' => 'Listamaður',
    ])->save();
  }
  if (!FieldStorageConfig::loadByName('node', 'field_artist_name')) {
  \Drupal\field\Entity\FieldStorageConfig::create([
    'field_name' => 'field_artist_name',
    'entity_type' => 'node',
    'type' => 'string',
  ])->save();
  }
  \Drupal\field\Entity\FieldConfig::create([
    'field_name' => 'field_artist_name',
    'entity_type' => 'node',
    'bundle' => 'artist',
    'label' => 'Artist Name',
  ])->save();
}
