<?php




/**
 * @file
 * Music Search module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\Entity\NodeType;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\field\Entity\FieldConfig;

/**
 * Implements hook_help().
 */
function music_search_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.music_search':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is an example module.') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_theme()
 */
function music_search_theme() {
  return [
    'music_search_page' => [
      'variables' =>['form' => NULL],
    ],
  ];
}


/**
 * Implements hook_install()
 *
 * Installs content types if they dont exist,
 * Makes this module movable to other projects
 */

function music_search_install() {
  if (!NodeType::load('listamadur')) {
    NodeType::create([
      'type' => 'listamadur',
      'name' => 'Listamaður',
    ])->save();
  }

  if (!NodeType::load('plata')) {
    NodeType::create([
      'type' => 'plata',
      'name' => 'Plata',
    ])->save();
  }

  if (!NodeType::load('lag')) {
    NodeType::create([
      'type' => 'lag',
      'name' => 'Lag',
    ])->save();
  }
}
